### PR TITLE
layer.conf: Switch LAYERSERIES_COMPAT to mickledore

### PR DESCRIPTION
**Pull request by kk6ho**
Signed-off-by: Geoff Parker <geoffrey.parker@arthrex.com>

### CODE REVIEW

**Comment by kk6ho** [comment]
THis will allow meta-java to be used on builds based on Yocto master which has switched its core layers from langdale to  mickledore.

I had sent this to the openembedded-devel mailing list a  week ago (Jan 7) but got no response nor seeing it in master or master-next.   Trying a PR this time.

**Comment by g0hl1n** [comment]
Hi,
sorry for the delay. I'm quite busy currently.

Is there a reason you removed support for the old releases?

**Comment by g0hl1n** [comment]
tbh the current situation (multiple releases in LAYERSERIES_COMPAT plus release branches) may be a bit misleading.

Personally I'm perfectly fine with limiting the LAYERSERIES_COMPAT to the release branch.
Although it might be a little backporting-overhead it is IMHO a cleaner approach than the current one.

As I'm currently refactoring my meta-java tests this may come in handy... But let me think a little bit about it. I'll come back to you. Until then I'll merge this into master-next.

regards;rl

**Comment by kk6ho** [comment]
Personally, I prefer a single release in LAYERSERIES_COMPAT also, even in
master. I think it is cleaner.

Having multiple layers listed is kind of a work-around when a layer has not
created a branch specific to a Yocto branch name.

Thanks.

**Comment by kk6ho** [comment]
Hi Richard,

I'm writing back to touchbase.   I haven't seen any changes to master or
master-next regarding switching LAYERSERIES_COMPAT to mickledore or
appending mickledore to it.  Also I notice that master-next is actually a
few commits behind master in the public repo.

-Geoff

**Comment by g0hl1n** [comment]
Thanks for the reminder.
The branches should be fine now.

**Comment by kk6ho** [comment]
Thanks Richard.

**Pull request merged**
